### ISSUE TITLE
Mise à disposition des sources

### ISSUE THREAD

**Issue by supermamie** [PierreBresson/cause-commune-app#1]
Bonjour,
J’utilise exclusivement des applications buildées par F-Droid sur mon téléphone.
https://f-droid.org/fr/

Cependant, pour ajouter des applications dans leur catalogue, il faut qu’ils la compilent eux même.

Est-il envisageable de rendre disponibles les sources de votre application ?

Merci d’avance !

**Comment by PierreBresson** [comment]
Bonjour,
Tu peux récupérer l'apk sur cette page pour l'installer sur ton android : https://github.com/PierreBresson/cause-commune-app/releases
J'ai déjà mis l'app Cause Commune sur Fdroid, mais je ne souhaite pas renouveller l'expérience.
